SRC =  scanner.c symtable.c param_list.c sym_stack.c expressions.c parser.c postfix_data_managment.c code_gen.c 
HEADERS = scanner.h errors.h symtable.h param_list.h sym_stack.h expressions.h parser.h postfix_data_managment.h code_gen.h errors.h

all:
	gcc -o ifj_project $(SRC) $(HEADERS) -lm
